name: Build Next JS Application

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build

      - name: Zip static export
        if: success()
        uses: papeloto/action-zip@v1
        with:
          files: out
          dest: next-build-${{ github.run_number }}.zip

      - name: Upload build artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: next-build-${{ github.run_number }}
          path: next-build-${{ github.run_number }}.zip
          if-no-files-found: error

  inspect-artifact:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: next-build-${{ github.run_number }}.zip